baseURL = '/'
languageCode = 'en-us'
title = 'Cristiioan'

theme = "smol"

# Parameters
[params]
    subtitle = "A blog about programming, technology, and life"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about/"
        weight = 1

  [[menu.main]]
        identifier = "links"
        name = "Useful links"
        url = "/links/"
        weight = 1

  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

# Footer

[[menu.footer]]
    name = "License"
    url = "/license/"
    identifier = "license"
    weight = 1

[[menu.footer]]
    name = "Github"
    url = "https://github.com/cristiioan"
    weight = 2

[[menu.footer]]
    name = "Matrix"
    url = "https://matrix.to/#/@cristiioan:cristiioan.me"
    weight = 3

[[menu.footer]]
    name = "Imprint"
    url = "/imprint"
    weight = 4

